apiVersion: v1
kind: Service
metadata:
  name: loki-lb
  namespace: loki
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: distributor
  ports:
    - name: http
      port: 3100
      protocol: TCP
      targetPort: 3100
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: grafana
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000